### PR TITLE
Implement hook_islandora_solution_pack_child_relationships().

### PR DESCRIPTION
**Pull request by jonathangreen**
## JIRA Ticket
https://jira.duraspace.org/browse/ISLANDORA-2294

Also see: 
https://github.com/Islandora/islandora/pull/710

## What does this Pull Request do?

Implements new hook defined in https://github.com/Islandora/islandora/pull/710

## How should this be tested?

Should be tested as part of https://github.com/Islandora/islandora/pull/710

## Interested parties
@DiegoPino

### CODE REVIEW

**Review by DiegoPino — COMMENTED** [review]
Ok, but after approving 2 other ones i just had second thoughts. 😢  Would it not be better if the magic key for "all" would be in the form of an empty array? or a NULL? makes keeping track of function signature a bit complicated. So, thoughts?

**Comment by jonathangreen** [comment]
I don't really have a preference. I thought 'all' was more descriptive then NULL, but I can change it however.

**Comment by DiegoPino** [comment]
@jonathangreen np, TBH i'm really opinion-less on D7 lately, just thought i needed to at least mention it. @Islandora/7-x-1-x-committers anyone? if no different opinion will go for "all" and will go on.

**Comment by whikloj** [comment]
`all` is fine, the key is to remain consistent. So if we start with `all` then people with get used to it.

**Review by DiegoPino — APPROVED** [review]

**Comment by DiegoPino** [comment]
Will merge before 24 hours... my bad but this needs to go with the others and had a 👍 since 4 days. Blame me, its all my fault.

**Pull request merged**
