### PR TITLE
Remove call to deprecated IslandoraBookDeprecateString. Address ISLAN…

### PR DESCRIPTION
**Pull request by ruebot**
…DORA-1511.

See: https://jira.duraspace.org/browse/ISLANDORA-1511
#182

### CODE REVIEW

**Comment by DiegoPino** [comment]
@ruebot,works fine at this side (and #182 ).  But before merging, just a question: why aren't we using this function
https://github.com/Islandora/islandora/blob/f6314d5a6189a9bdbc902535c72ab2ba2ef39306/includes/solution_packs.inc#L792. I see we are duplicating code…appears to be also in other modules.

**Comment by DiegoPino** [comment]
Hey! de nada :smile:

**Comment by adam-vessey** [comment]
@DiegoPino @ruebot Avoiding `islandora_get_viewer()` was [intentional](https://github.com/Islandora/islandora_solution_pack_book/pull/163/files#diff-8964427b21f6180b29573c0367f4b3e6L49), so we can provide different settings (instead of just always [`variable_get()`ing](https://github.com/Islandora/islandora/blob/7b69eb32c25338e1b037b33ca999d69f7d25cbee/includes/solution_packs.inc#L793)). I don't recall right off, but I believe this was to allow the viewer to be changed without changing global configuration (by adjusting things during preprocessing).

**Comment by DiegoPino** [comment]
@adam-vessey thanks.

**Pull request merged**
