### PR TITLE
DESTROY ISLANDORACM!!!

### PR DESCRIPTION
**Pull request by ruebot**

### CODE REVIEW

**Comment by qadan** [comment]
@ruebot; I just tried using this pull on a brand-new install. Seems that chopping those collection policy XML files gave me a lot of grief when attempting to install the module, view admin/islandora/solution_pack_config/solution_packs, and view the actual book collection (I didn't try anything beyond there) ... is there another pull involved with this (perhaps to islandora_basic_collection) that would resolve these?

Edit: specifically, the errors I was getting from installing the solution pack were the ones that Travis is complaining about.

**Comment by qadan** [comment]
A-haaaaaa, so I guess we'll have to re-run these tests when that's merged

**Comment by qadan** [comment]
boo-urns. i'll take a look

**Comment by qadan** [comment]
Running every module on HEAD on a brand-new VM, including the above-mentioned merged PR, I'm still getting the same exceptions flagged by Travis:

During install of the module (from scratch):
screen shot 2014-09-12 at 10 20 46 am

Looking at admin/islandora/solution_pack_config/solution_packs:
screen shot 2014-09-12 at 10 25 05 am

Trying to look at the Book Collection:
screen shot 2014-09-12 at 10 26 00 am

http://youtu.be/1ytCEuuW2_A

**Comment by qadan** [comment]
No problem! Happy to poke at things :)

**Comment by willtp87** [comment]
I like -a :)

**Pull request merged**
